config:
  aws:region: us-east-1
  info-helper-infra:ecrRepositoryName: info-helper-dev
  info-helper-infra:sesSenderEmail:
    secure: AAABACvvMSgut5kR18FGC/0V9lJjTgWAsmuBLZfBvxE3ITmv2xag3RperwkEfRdcWUg=
  info-helper-infra:vpcCidr: 10.0.0.0/16
